[package]
name = "proc_macro_lang"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "core_engine",
    "lang_macro",
    "runtime"
]

[dependencies]
lang_macro = { path = "lang_macro" }
core_engine = { path = "core_engine" }
runtime = { path = "runtime" }

