[package]
name = "core_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = { version = "1.0.93", features = ["span-locations"] }
syn = {version="2.0.96",features=[]}
# synom = "0.11.3"